-- Migration 007: Comprehensive Marketplace Seed
-- Phase 2: Populate marketplace with 100+ popular integrations
-- Created: 2026-01-18
-- Purpose: Provide a rich marketplace experience without relying on n8n API

-- Clear existing data and start fresh
TRUNCATE integration_marketplace CASCADE;

-- =============================================================================
-- CALENDAR & SCHEDULING (15 integrations)
-- =============================================================================

INSERT INTO integration_marketplace (
  slug, name, category, description, long_description, icon_url,
  requires_auth, auth_type, pricing_model, is_featured, is_direct_integration,
  recommended_for_verticals, supported_features, n8n_node_name, popularity_score,
  setup_instructions, documentation_url
) VALUES

('google-calendar', 'Google Calendar', 'calendar',
 'Schedule appointments and manage availability',
 'Sync your WhatsApp bot with Google Calendar to automatically schedule appointments, check availability, and send reminders. Perfect for medical practices, salons, gyms, and any appointment-based business.',
 'https://www.gstatic.com/images/branding/product/2x/calendar_48dp.png',
 true, 'oauth2', 'free', true, true,
 ARRAY['medical', 'doctor', 'salon', 'gym', 'hotel', 'real_estate'],
 ARRAY['create_event', 'check_availability', 'send_reminders', 'update_event', 'cancel_event', 'recurring_events'],
 'n8n-nodes-base.googleCalendar', 98,
 '{"steps": ["Go to Google Cloud Console", "Create project", "Enable Calendar API", "Create OAuth credentials"]}'::jsonb,
 'https://developers.google.com/calendar/api/'),

('calendly', 'Calendly', 'calendar',
 'Professional appointment scheduling',
 'Connect Calendly to let customers book appointments directly through WhatsApp. Handles availability, time zones, and automated reminders.',
 'https://assets.calendly.com/assets/frontend/media/logo-square-cd364a3a70b605f5e97c.png',
 true, 'api_key', 'freemium', true, true,
 ARRAY['medical', 'doctor', 'salon', 'gym', 'real_estate'],
 ARRAY['create_booking', 'check_availability', 'webhook_notifications', 'event_types'],
 'n8n-nodes-base.calendly', 92,
 '{"steps": ["Log in to Calendly", "Go to Integrations", "Generate API key"]}'::jsonb,
 'https://developer.calendly.com/'),

('microsoft-outlook', 'Microsoft Outlook Calendar', 'calendar',
 'Office 365 calendar integration',
 'Sync with Microsoft Outlook Calendar for enterprise appointment scheduling and team coordination.',
 'https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['create_event', 'check_availability', 'send_invites', 'recurring_events'],
 'n8n-nodes-base.microsoftOutlook', 85,
 '{"steps": ["Register app in Azure AD", "Configure permissions", "Get client credentials"]}'::jsonb,
 'https://docs.microsoft.com/en-us/graph/api/resources/calendar'),

('cal-com', 'Cal.com', 'calendar',
 'Open-source scheduling platform',
 'Self-hosted or cloud scheduling with full control. Perfect for privacy-conscious businesses.',
 'https://cal.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['create_booking', 'availability', 'event_types', 'webhooks'],
 'n8n-nodes-base.cal', 75,
 '{"steps": ["Log in to Cal.com", "Go to Settings > API Keys", "Generate new key"]}'::jsonb,
 'https://cal.com/docs/api'),

('acuity-scheduling', 'Acuity Scheduling', 'calendar',
 'Client scheduling for professionals',
 'Powerful scheduling for consultants, coaches, and service providers with payment integration.',
 'https://acuityscheduling.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['salon', 'gym', 'medical'],
 ARRAY['appointments', 'availability', 'payments', 'packages'],
 'n8n-nodes-base.acuityScheduling', 78,
 '{"steps": ["Log in to Acuity", "Go to Integrations > API", "Copy API credentials"]}'::jsonb,
 'https://developers.acuityscheduling.com/'),

('setmore', 'Setmore', 'calendar',
 'Free appointment scheduling',
 'Simple and free appointment scheduling with online booking pages.',
 'https://www.setmore.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['salon', 'medical', 'gym'],
 ARRAY['appointments', 'staff_management', 'notifications'],
 'custom', 65,
 '{"steps": ["Sign up for Setmore", "Go to Settings > Integrations", "Get API key"]}'::jsonb,
 'https://www.setmore.com/'),

('booksy', 'Booksy', 'calendar',
 'Beauty & wellness booking',
 'Specialized booking platform for salons, barbershops, and beauty professionals.',
 'https://booksy.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['salon'],
 ARRAY['appointments', 'staff_calendar', 'client_management'],
 'custom', 70,
 '{"steps": ["Contact Booksy for API access", "Get API credentials"]}'::jsonb,
 'https://booksy.com/'),

('simplybook', 'SimplyBook.me', 'calendar',
 'Multi-purpose booking system',
 'Flexible booking system with custom forms, payments, and multi-location support.',
 'https://simplybook.me/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['bookings', 'services', 'providers', 'custom_forms'],
 'custom', 72,
 '{"steps": ["Log in to SimplyBook", "Go to Custom Features > API", "Enable and copy key"]}'::jsonb,
 'https://simplybook.me/'),

('ical-sync', 'iCal Sync', 'calendar',
 'Universal calendar sync',
 'Sync with any calendar that supports iCal format - Airbnb, Booking.com, VRBO, and more.',
 '/integrations/ical.png',
 false, null, 'free', true, true,
 ARRAY['airbnb', 'hotel'],
 ARRAY['import_events', 'export_events', 'availability_sync', 'multi_calendar'],
 'custom', 88,
 '{"steps": ["Get iCal URL from your calendar service", "Paste URL in BotFlow", "Set sync interval"]}'::jsonb,
 'https://icalendar.org/'),

('mindbody', 'Mindbody', 'calendar',
 'Fitness & wellness software',
 'Complete business management for fitness studios, gyms, and wellness centers.',
 'https://www.mindbodyonline.com/favicon.ico',
 true, 'oauth2', 'paid', false, true,
 ARRAY['gym', 'salon'],
 ARRAY['classes', 'appointments', 'memberships', 'payments'],
 'custom', 80,
 '{"steps": ["Apply for Mindbody API access", "Complete developer agreement", "Get API credentials"]}'::jsonb,
 'https://developers.mindbodyonline.com/'),

-- =============================================================================
-- E-COMMERCE (20 integrations)
-- =============================================================================

('shopify', 'Shopify', 'ecommerce',
 'E-commerce store integration',
 'Connect your Shopify store to WhatsApp for order tracking, inventory checks, product search, and customer support.',
 'https://cdn.shopify.com/shopifycloud/brochure/assets/brand-assets/shopify-logo-primary-logo-456baa801ee66a0a435671082365958316831c9960c480451dd0330bcdae304f.svg',
 true, 'api_key', 'free', true, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['order_tracking', 'inventory_check', 'product_search', 'create_order', 'customer_lookup'],
 'n8n-nodes-base.shopify', 96,
 '{"steps": ["Log in to Shopify admin", "Go to Apps > Develop apps", "Create app and get credentials"]}'::jsonb,
 'https://shopify.dev/docs/'),

('woocommerce', 'WooCommerce', 'ecommerce',
 'WordPress e-commerce integration',
 'Integrate WooCommerce with WhatsApp for order management, inventory tracking, and customer notifications.',
 'https://woocommerce.com/wp-content/themes/flavor/favicon-32x32.png',
 true, 'api_key', 'free', true, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['order_tracking', 'inventory_check', 'product_catalog', 'customer_management'],
 'n8n-nodes-base.wooCommerce', 94,
 '{"steps": ["Go to WooCommerce > Settings > Advanced > REST API", "Add key", "Copy credentials"]}'::jsonb,
 'https://woocommerce.github.io/woocommerce-rest-api-docs/'),

('magento', 'Magento / Adobe Commerce', 'ecommerce',
 'Enterprise e-commerce platform',
 'Connect Adobe Commerce (Magento) for enterprise-level order management and inventory control.',
 'https://magento.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'customers', 'inventory'],
 'n8n-nodes-base.magento', 82,
 '{"steps": ["Go to System > Integrations", "Create new integration", "Copy access tokens"]}'::jsonb,
 'https://devdocs.magento.com/'),

('bigcommerce', 'BigCommerce', 'ecommerce',
 'Scalable e-commerce solution',
 'Enterprise e-commerce with built-in features for growing businesses.',
 'https://www.bigcommerce.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'customers', 'shipping'],
 'n8n-nodes-base.bigCommerce', 78,
 '{"steps": ["Go to Advanced Settings > API Accounts", "Create V2/V3 API Account"]}'::jsonb,
 'https://developer.bigcommerce.com/'),

('prestashop', 'PrestaShop', 'ecommerce',
 'Open-source e-commerce',
 'Free and open-source e-commerce platform with extensive customization options.',
 'https://www.prestashop.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'customers', 'stock'],
 'n8n-nodes-base.prestaShop', 70,
 '{"steps": ["Go to Advanced Parameters > Webservice", "Enable webservice", "Generate API key"]}'::jsonb,
 'https://devdocs.prestashop-project.org/'),

('square-ecommerce', 'Square Online', 'ecommerce',
 'All-in-one commerce platform',
 'Unified online and in-person selling with integrated payments.',
 'https://squareup.com/favicon.ico',
 true, 'oauth2', 'freemium', false, true,
 ARRAY['retail', 'restaurant'],
 ARRAY['orders', 'catalog', 'inventory', 'payments'],
 'n8n-nodes-base.square', 75,
 '{"steps": ["Create Square Developer account", "Create application", "Get OAuth credentials"]}'::jsonb,
 'https://developer.squareup.com/'),

('ecwid', 'Ecwid', 'ecommerce',
 'Embeddable online store',
 'Add e-commerce to any website or social media with Ecwid.',
 'https://www.ecwid.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'customers', 'shipping'],
 'custom', 68,
 '{"steps": ["Go to Ecwid Control Panel", "Apps > My Apps", "Create new app for API access"]}'::jsonb,
 'https://api-docs.ecwid.com/'),

('etsy', 'Etsy', 'ecommerce',
 'Handmade & vintage marketplace',
 'Connect your Etsy shop for order notifications and inventory management.',
 'https://www.etsy.com/favicon.ico',
 true, 'oauth2', 'free', false, true,
 ARRAY['ecommerce'],
 ARRAY['orders', 'listings', 'inventory', 'reviews'],
 'n8n-nodes-base.etsy', 72,
 '{"steps": ["Register as Etsy developer", "Create new app", "Get API credentials"]}'::jsonb,
 'https://developers.etsy.com/'),

('amazon-seller', 'Amazon Seller Central', 'ecommerce',
 'Amazon marketplace integration',
 'Manage Amazon orders, inventory, and customer messages through WhatsApp.',
 'https://sellercentral.amazon.com/favicon.ico',
 true, 'oauth2', 'free', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'inventory', 'fulfillment', 'reports'],
 'n8n-nodes-base.amazonSeller', 85,
 '{"steps": ["Register in Amazon Developer Portal", "Create MWS credentials", "Configure selling partner API"]}'::jsonb,
 'https://developer-docs.amazon.com/sp-api/'),

('ebay', 'eBay', 'ecommerce',
 'Global online marketplace',
 'Connect eBay for listing management, order tracking, and buyer communication.',
 'https://www.ebay.com/favicon.ico',
 true, 'oauth2', 'free', false, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'listings', 'inventory', 'messaging'],
 'n8n-nodes-base.eBay', 75,
 '{"steps": ["Join eBay Developers Program", "Create application keys", "Configure OAuth"]}'::jsonb,
 'https://developer.ebay.com/'),

('takealot', 'Takealot', 'ecommerce',
 'South African online marketplace',
 'Connect to South Africa''s largest online retailer for order management.',
 '/integrations/takealot.png',
 true, 'api_key', 'free', true, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'inventory', 'fulfillment'],
 'custom', 80,
 '{"steps": ["Contact Takealot Seller Support", "Request API access", "Get credentials"]}'::jsonb,
 'https://www.takealot.com/'),

('bob-shop', 'Bob Shop', 'ecommerce',
 'South African marketplace',
 'South African online marketplace integration for sellers.',
 '/integrations/bobshop.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'inventory'],
 'custom', 60,
 '{"steps": ["Contact Bob Shop for API access", "Get credentials"]}'::jsonb,
 'https://www.bobshop.co.za/'),

-- =============================================================================
-- PAYMENT PROCESSING (15 integrations)
-- =============================================================================

('stripe', 'Stripe', 'payment',
 'Accept payments via WhatsApp',
 'Process payments securely through Stripe directly in your WhatsApp conversations. Create payment links, process refunds, and manage subscriptions.',
 'https://images.ctfassets.net/fzn2n1nzq965/HTTOloNPhisV9P4hlMPNA/cacf1bb88b9fc492dfad34378d844280/Stripe_icon_-_square.svg',
 true, 'api_key', 'free', true, true,
 ARRAY['ecommerce', 'retail', 'gym', 'salon', 'restaurant'],
 ARRAY['create_payment_link', 'process_payment', 'refund', 'subscription_management'],
 'n8n-nodes-base.stripe', 97,
 '{"steps": ["Log in to Stripe Dashboard", "Go to Developers > API keys", "Copy Secret key"]}'::jsonb,
 'https://stripe.com/docs/api'),

('paystack', 'Paystack', 'payment',
 'African payment gateway',
 'Accept payments from African customers. Supports card payments, bank transfers, and mobile money.',
 'https://paystack.com/assets/img/logos/paystack-icon.svg',
 true, 'api_key', 'free', true, true,
 ARRAY['ecommerce', 'retail', 'gym', 'salon', 'restaurant'],
 ARRAY['create_payment', 'verify_payment', 'refund', 'subscriptions'],
 'n8n-nodes-base.paystack', 90,
 '{"steps": ["Log in to Paystack", "Go to Settings > API Keys", "Copy Secret Key"]}'::jsonb,
 'https://paystack.com/docs/api/'),

('paypal', 'PayPal', 'payment',
 'Global payment platform',
 'Accept PayPal payments, send money, and manage transactions worldwide.',
 'https://www.paypalobjects.com/webstatic/icon/pp258.png',
 true, 'oauth2', 'free', true, true,
 ARRAY['ecommerce', 'retail'],
 ARRAY['payments', 'refunds', 'invoices', 'subscriptions'],
 'n8n-nodes-base.payPal', 93,
 '{"steps": ["Create PayPal Developer account", "Create REST API app", "Get client ID and secret"]}'::jsonb,
 'https://developer.paypal.com/'),

('square-payments', 'Square Payments', 'payment',
 'In-person and online payments',
 'Unified payment processing for retail, restaurants, and service businesses.',
 'https://squareup.com/favicon.ico',
 true, 'oauth2', 'free', false, true,
 ARRAY['retail', 'restaurant'],
 ARRAY['payments', 'refunds', 'invoices', 'terminals'],
 'n8n-nodes-base.square', 82,
 '{"steps": ["Create Square Developer account", "Create application", "Get credentials"]}'::jsonb,
 'https://developer.squareup.com/'),

('peach-payments', 'Peach Payments', 'payment',
 'South African payment gateway',
 'Local South African payment gateway supporting multiple payment methods.',
 '/integrations/peach.png',
 true, 'api_key', 'free', true, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['card_payments', 'eft', 'instant_eft', 'mobicred'],
 'custom', 78,
 '{"steps": ["Contact Peach Payments", "Complete merchant onboarding", "Get API credentials"]}'::jsonb,
 'https://www.peachpayments.com/'),

('yoco', 'Yoco', 'payment',
 'South African card payments',
 'Accept card payments in South Africa with Yoco card machines and online payments.',
 '/integrations/yoco.png',
 true, 'api_key', 'free', true, false,
 ARRAY['retail', 'restaurant'],
 ARRAY['card_payments', 'payment_links', 'refunds'],
 'custom', 82,
 '{"steps": ["Sign up for Yoco", "Go to Dashboard > Developers", "Generate API key"]}'::jsonb,
 'https://developer.yoco.com/'),

('snapscan', 'SnapScan', 'payment',
 'QR code payments',
 'South African QR code payment solution for easy mobile payments.',
 '/integrations/snapscan.png',
 true, 'api_key', 'free', false, false,
 ARRAY['retail', 'restaurant'],
 ARRAY['qr_payments', 'payment_requests', 'notifications'],
 'custom', 70,
 '{"steps": ["Register as SnapScan merchant", "Get API credentials from merchant portal"]}'::jsonb,
 'https://www.snapscan.co.za/'),

('ozow', 'Ozow', 'payment',
 'Instant EFT payments',
 'South African instant EFT payment solution for secure bank transfers.',
 '/integrations/ozow.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['instant_eft', 'payment_status', 'refunds'],
 'custom', 72,
 '{"steps": ["Register with Ozow", "Complete merchant verification", "Get API credentials"]}'::jsonb,
 'https://ozow.com/'),

('wise', 'Wise (TransferWise)', 'payment',
 'International transfers',
 'Send and receive international payments with real exchange rates.',
 'https://wise.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['all'],
 ARRAY['transfers', 'quotes', 'recipients', 'balance'],
 'n8n-nodes-base.wise', 75,
 '{"steps": ["Log in to Wise", "Go to Settings > API tokens", "Create new token"]}'::jsonb,
 'https://api-docs.wise.com/'),

('gocardless', 'GoCardless', 'payment',
 'Direct debit payments',
 'Collect recurring payments via bank debit. Perfect for subscriptions and memberships.',
 'https://gocardless.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['gym', 'all'],
 ARRAY['direct_debit', 'subscriptions', 'mandates', 'payments'],
 'n8n-nodes-base.gocardless', 70,
 '{"steps": ["Create GoCardless account", "Go to Developers", "Create access token"]}'::jsonb,
 'https://developer.gocardless.com/'),

-- =============================================================================
-- CRM (15 integrations)
-- =============================================================================

('hubspot', 'HubSpot', 'crm',
 'All-in-one CRM platform',
 'Sync WhatsApp conversations with HubSpot CRM for unified customer data. Create contacts, update deals, and log interactions.',
 'https://www.hubspot.com/hubfs/HubSpot_Logos/HubSpot-Inversed-Favicon.png',
 true, 'oauth2', 'freemium', true, true,
 ARRAY['real_estate', 'gym', 'salon', 'all'],
 ARRAY['create_contact', 'update_contact', 'create_deal', 'log_activity', 'sync_conversations'],
 'n8n-nodes-base.hubspot', 95,
 '{"steps": ["Log in to HubSpot", "Go to Settings > Integrations > Private Apps", "Create app and get token"]}'::jsonb,
 'https://developers.hubspot.com/'),

('salesforce', 'Salesforce', 'crm',
 'Enterprise CRM solution',
 'Connect Salesforce to track leads, opportunities, and customer interactions from WhatsApp.',
 'https://www.salesforce.com/content/dam/sfdc-docs/www/logos/logo-salesforce.svg',
 true, 'oauth2', 'paid', false, true,
 ARRAY['real_estate', 'all'],
 ARRAY['leads', 'contacts', 'opportunities', 'activities', 'cases'],
 'n8n-nodes-base.salesforce', 88,
 '{"steps": ["Go to Setup > Apps > App Manager", "Create Connected App", "Get OAuth credentials"]}'::jsonb,
 'https://developer.salesforce.com/'),

('pipedrive', 'Pipedrive', 'crm',
 'Sales-focused CRM',
 'Visual sales pipeline CRM for small and medium businesses.',
 'https://www.pipedrive.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['real_estate', 'all'],
 ARRAY['deals', 'persons', 'organizations', 'activities', 'notes'],
 'n8n-nodes-base.pipedrive', 82,
 '{"steps": ["Go to Settings > Personal preferences", "API", "Copy your personal API token"]}'::jsonb,
 'https://developers.pipedrive.com/'),

('zoho-crm', 'Zoho CRM', 'crm',
 'Comprehensive CRM suite',
 'Full-featured CRM with sales automation, analytics, and multichannel communication.',
 'https://www.zoho.com/favicon.ico',
 true, 'oauth2', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['leads', 'contacts', 'deals', 'accounts', 'tasks'],
 'n8n-nodes-base.zohoCrm', 80,
 '{"steps": ["Go to Zoho API Console", "Create self-client", "Generate tokens"]}'::jsonb,
 'https://www.zoho.com/crm/developer/'),

('freshsales', 'Freshsales', 'crm',
 'AI-powered CRM',
 'Smart CRM with AI-based lead scoring, built-in phone, and email.',
 'https://www.freshworks.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['contacts', 'leads', 'deals', 'accounts', 'tasks'],
 'n8n-nodes-base.freshsales', 75,
 '{"steps": ["Go to Admin Settings", "API Settings", "Copy API key"]}'::jsonb,
 'https://developers.freshsales.io/'),

('copper', 'Copper CRM', 'crm',
 'Google Workspace CRM',
 'CRM built for Google Workspace with automatic data capture.',
 'https://www.copper.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['leads', 'people', 'companies', 'opportunities', 'activities'],
 'n8n-nodes-base.copper', 70,
 '{"steps": ["Go to Settings > Integrations", "API Keys", "Generate new key"]}'::jsonb,
 'https://developer.copper.com/'),

('monday-crm', 'monday sales CRM', 'crm',
 'Visual CRM platform',
 'Customizable CRM built on monday.com work OS.',
 'https://monday.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['items', 'boards', 'updates', 'contacts'],
 'n8n-nodes-base.mondayCom', 78,
 '{"steps": ["Go to Admin > API", "Generate new token"]}'::jsonb,
 'https://developer.monday.com/'),

('close', 'Close CRM', 'crm',
 'Inside sales CRM',
 'CRM designed for inside sales teams with built-in calling and email.',
 'https://close.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['leads', 'contacts', 'activities', 'opportunities', 'tasks'],
 'n8n-nodes-base.closeCom', 72,
 '{"steps": ["Go to Settings > API Keys", "Create new API key"]}'::jsonb,
 'https://developer.close.com/'),

-- =============================================================================
-- COMMUNICATION (20 integrations)
-- =============================================================================

('slack', 'Slack', 'communication',
 'Team messaging platform',
 'Send WhatsApp conversation notifications to Slack channels. Alert your team about important messages and leads.',
 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
 true, 'oauth2', 'free', true, true,
 ARRAY['all'],
 ARRAY['send_message', 'send_notification', 'create_channel', 'upload_file'],
 'n8n-nodes-base.slack', 92,
 '{"steps": ["Go to api.slack.com/apps", "Create New App", "Add Bot Token Scopes", "Install to Workspace"]}'::jsonb,
 'https://api.slack.com/'),

('microsoft-teams', 'Microsoft Teams', 'communication',
 'Enterprise collaboration',
 'Send notifications and alerts to Microsoft Teams channels.',
 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['send_message', 'channels', 'teams', 'chats'],
 'n8n-nodes-base.microsoftTeams', 85,
 '{"steps": ["Register app in Azure AD", "Configure Teams permissions", "Get credentials"]}'::jsonb,
 'https://docs.microsoft.com/en-us/graph/teams-concept-overview'),

('gmail', 'Gmail', 'communication',
 'Email integration',
 'Send emails from WhatsApp conversations. Perfect for order confirmations, receipts, and follow-ups.',
 'https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['send_email', 'read_email', 'search_email', 'attachments'],
 'n8n-nodes-base.gmail', 88,
 '{"steps": ["Go to Google Cloud Console", "Enable Gmail API", "Create OAuth credentials"]}'::jsonb,
 'https://developers.google.com/gmail/api/'),

('outlook-mail', 'Microsoft Outlook', 'communication',
 'Office 365 email',
 'Send and manage emails through Microsoft Outlook integration.',
 'https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['send_email', 'read_email', 'calendar', 'contacts'],
 'n8n-nodes-base.microsoftOutlook', 82,
 '{"steps": ["Register in Azure AD", "Configure Mail permissions", "Get credentials"]}'::jsonb,
 'https://docs.microsoft.com/en-us/graph/outlook-mail-concept-overview'),

('sendgrid', 'SendGrid', 'communication',
 'Email delivery service',
 'Reliable email delivery for transactional and marketing emails.',
 'https://sendgrid.com/wp-content/themes/flavor/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['send_email', 'templates', 'contacts', 'stats'],
 'n8n-nodes-base.sendGrid', 80,
 '{"steps": ["Log in to SendGrid", "Go to Settings > API Keys", "Create API Key"]}'::jsonb,
 'https://docs.sendgrid.com/'),

('mailchimp', 'Mailchimp', 'communication',
 'Email marketing platform',
 'Add WhatsApp contacts to Mailchimp lists and trigger email campaigns.',
 'https://mailchimp.com/release/plums/cxp/images/favicon-v2.ico',
 true, 'api_key', 'freemium', true, true,
 ARRAY['ecommerce', 'retail', 'all'],
 ARRAY['add_subscriber', 'campaigns', 'audiences', 'automations'],
 'n8n-nodes-base.mailchimp', 87,
 '{"steps": ["Log in to Mailchimp", "Go to Account > Extras > API keys", "Create Key"]}'::jsonb,
 'https://mailchimp.com/developer/'),

('twilio-sms', 'Twilio SMS', 'communication',
 'SMS messaging',
 'Send SMS messages to customers alongside WhatsApp.',
 'https://www.twilio.com/assets/images/brand/twilio-logo-red.svg',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['send_sms', 'lookup', 'verify'],
 'n8n-nodes-base.twilio', 85,
 '{"steps": ["Log in to Twilio Console", "Get Account SID and Auth Token"]}'::jsonb,
 'https://www.twilio.com/docs/'),

('discord', 'Discord', 'communication',
 'Community messaging',
 'Send notifications to Discord channels for community management.',
 'https://discord.com/assets/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['all'],
 ARRAY['send_message', 'webhooks', 'embeds'],
 'n8n-nodes-base.discord', 75,
 '{"steps": ["Go to Discord Developer Portal", "Create Application", "Add Bot", "Copy Token"]}'::jsonb,
 'https://discord.com/developers/docs/'),

('telegram', 'Telegram Bot', 'communication',
 'Telegram integration',
 'Send messages to Telegram alongside WhatsApp for multi-channel communication.',
 'https://telegram.org/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['all'],
 ARRAY['send_message', 'send_photo', 'send_document', 'webhooks'],
 'n8n-nodes-base.telegram', 78,
 '{"steps": ["Message @BotFather on Telegram", "Create new bot", "Copy API token"]}'::jsonb,
 'https://core.telegram.org/bots/api'),

('intercom', 'Intercom', 'communication',
 'Customer messaging platform',
 'Sync WhatsApp conversations with Intercom for unified customer support.',
 'https://www.intercom.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['contacts', 'conversations', 'messages', 'tags'],
 'n8n-nodes-base.intercom', 80,
 '{"steps": ["Go to Settings > Developers", "Create new app", "Copy Access Token"]}'::jsonb,
 'https://developers.intercom.com/'),

('zendesk', 'Zendesk', 'communication',
 'Customer service platform',
 'Create support tickets from WhatsApp conversations and sync customer data.',
 'https://www.zendesk.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['tickets', 'users', 'organizations', 'comments'],
 'n8n-nodes-base.zendesk', 82,
 '{"steps": ["Go to Admin > API", "Enable API access", "Create API token"]}'::jsonb,
 'https://developer.zendesk.com/'),

('freshdesk', 'Freshdesk', 'communication',
 'Helpdesk software',
 'Convert WhatsApp messages into support tickets automatically.',
 'https://www.freshworks.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['tickets', 'contacts', 'agents', 'groups'],
 'n8n-nodes-base.freshdesk', 78,
 '{"steps": ["Go to Admin > Profile Settings", "Get your API key"]}'::jsonb,
 'https://developers.freshdesk.com/'),

-- =============================================================================
-- PRODUCTIVITY (20 integrations)
-- =============================================================================

('google-sheets', 'Google Sheets', 'productivity',
 'Spreadsheet integration',
 'Log conversation data, track leads, manage inventory in Google Sheets. Automatically update rows based on WhatsApp interactions.',
 'https://www.gstatic.com/images/branding/product/2x/sheets_48dp.png',
 true, 'oauth2', 'free', true, true,
 ARRAY['all'],
 ARRAY['append_row', 'update_row', 'read_data', 'create_sheet', 'lookup'],
 'n8n-nodes-base.googleSheets', 96,
 '{"steps": ["Go to Google Cloud Console", "Enable Sheets API", "Create OAuth credentials"]}'::jsonb,
 'https://developers.google.com/sheets/api/'),

('airtable', 'Airtable', 'productivity',
 'Database & spreadsheet hybrid',
 'Store and manage WhatsApp conversation data in Airtable bases. Perfect for tracking leads, inventory, and bookings.',
 'https://airtable.com/favicon.ico',
 true, 'api_key', 'freemium', true, true,
 ARRAY['all'],
 ARRAY['create_record', 'update_record', 'search', 'list_records'],
 'n8n-nodes-base.airtable', 90,
 '{"steps": ["Go to Account > API", "Generate API key", "Copy Base ID from docs"]}'::jsonb,
 'https://airtable.com/developers/web/api/'),

('notion', 'Notion', 'productivity',
 'All-in-one workspace',
 'Connect Notion to create databases, update pages, and manage your team workspace from WhatsApp.',
 'https://www.notion.so/favicon.ico',
 true, 'api_key', 'freemium', true, true,
 ARRAY['all'],
 ARRAY['create_page', 'update_page', 'databases', 'blocks'],
 'n8n-nodes-base.notion', 92,
 '{"steps": ["Go to Settings & Members", "Integrations", "Create new integration"]}'::jsonb,
 'https://developers.notion.com/'),

('trello', 'Trello', 'productivity',
 'Kanban boards',
 'Manage Trello boards, cards, and lists from WhatsApp. Create tasks and track progress.',
 'https://trello.com/favicon.ico',
 true, 'api_key', 'free', false, true,
 ARRAY['all'],
 ARRAY['create_card', 'update_card', 'move_card', 'boards', 'lists'],
 'n8n-nodes-base.trello', 85,
 '{"steps": ["Go to trello.com/power-ups/admin", "Generate API Key and Token"]}'::jsonb,
 'https://developer.atlassian.com/cloud/trello/'),

('asana', 'Asana', 'productivity',
 'Project management',
 'Create and manage Asana tasks, projects, and workflows from WhatsApp conversations.',
 'https://asana.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['create_task', 'update_task', 'projects', 'sections'],
 'n8n-nodes-base.asana', 82,
 '{"steps": ["Go to Account Settings > Apps > Developer apps", "Create token"]}'::jsonb,
 'https://developers.asana.com/'),

('monday', 'monday.com', 'productivity',
 'Work operating system',
 'Integrate monday.com to manage boards, items, and workflows from WhatsApp.',
 'https://monday.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['items', 'boards', 'updates', 'columns'],
 'n8n-nodes-base.mondayCom', 80,
 '{"steps": ["Go to Admin > API", "Generate API token"]}'::jsonb,
 'https://developer.monday.com/'),

('clickup', 'ClickUp', 'productivity',
 'All-in-one productivity',
 'Manage ClickUp tasks, docs, and goals from WhatsApp.',
 'https://clickup.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['tasks', 'lists', 'folders', 'spaces'],
 'n8n-nodes-base.clickUp', 78,
 '{"steps": ["Go to Settings > Apps", "Generate API Token"]}'::jsonb,
 'https://clickup.com/api/'),

('jira', 'Jira', 'productivity',
 'Issue tracking',
 'Create and manage Jira issues from WhatsApp. Perfect for support escalations.',
 'https://www.atlassian.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['issues', 'projects', 'comments', 'transitions'],
 'n8n-nodes-base.jira', 80,
 '{"steps": ["Go to Account Settings > Security > API tokens", "Create API token"]}'::jsonb,
 'https://developer.atlassian.com/cloud/jira/'),

('basecamp', 'Basecamp', 'productivity',
 'Project collaboration',
 'Connect Basecamp for project and team management.',
 'https://basecamp.com/favicon.ico',
 true, 'oauth2', 'paid', false, true,
 ARRAY['all'],
 ARRAY['projects', 'todos', 'messages', 'comments'],
 'n8n-nodes-base.basecamp', 68,
 '{"steps": ["Go to basecamp.com/launchpad", "Register your application"]}'::jsonb,
 'https://github.com/basecamp/bc3-api'),

('todoist', 'Todoist', 'productivity',
 'Task management',
 'Create and manage tasks from WhatsApp conversations.',
 'https://todoist.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['tasks', 'projects', 'labels', 'comments'],
 'n8n-nodes-base.todoist', 75,
 '{"steps": ["Go to Settings > Integrations > API token", "Copy token"]}'::jsonb,
 'https://developer.todoist.com/'),

('google-drive', 'Google Drive', 'productivity',
 'Cloud storage',
 'Upload files, create documents, and manage Google Drive from WhatsApp.',
 'https://www.gstatic.com/images/branding/product/2x/drive_48dp.png',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['upload', 'download', 'create_folder', 'share'],
 'n8n-nodes-base.googleDrive', 88,
 '{"steps": ["Go to Google Cloud Console", "Enable Drive API", "Create OAuth credentials"]}'::jsonb,
 'https://developers.google.com/drive/api/'),

('dropbox', 'Dropbox', 'productivity',
 'File storage',
 'Store and share files through Dropbox integration.',
 'https://www.dropbox.com/favicon.ico',
 true, 'oauth2', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['upload', 'download', 'share', 'folders'],
 'n8n-nodes-base.dropbox', 78,
 '{"steps": ["Go to Dropbox App Console", "Create app", "Get access token"]}'::jsonb,
 'https://www.dropbox.com/developers/'),

('onedrive', 'OneDrive', 'productivity',
 'Microsoft cloud storage',
 'Manage files and folders in OneDrive from WhatsApp.',
 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Microsoft_Office_OneDrive_%282019%E2%80%93present%29.svg',
 true, 'oauth2', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['upload', 'download', 'share', 'folders'],
 'n8n-nodes-base.microsoftOneDrive', 75,
 '{"steps": ["Register app in Azure AD", "Configure OneDrive permissions"]}'::jsonb,
 'https://docs.microsoft.com/en-us/graph/onedrive-concept-overview'),

('wordpress', 'WordPress', 'productivity',
 'CMS integration',
 'Create posts, manage content, and moderate comments from WhatsApp.',
 'https://s.w.org/style/images/about/WordPress-logotype-wmark.png',
 true, 'api_key', 'free', false, true,
 ARRAY['all'],
 ARRAY['posts', 'pages', 'comments', 'media'],
 'n8n-nodes-base.wordpress', 82,
 '{"steps": ["Go to Users > Profile", "Application Passwords", "Create password"]}'::jsonb,
 'https://developer.wordpress.org/rest-api/'),

-- =============================================================================
-- ANALYTICS (10 integrations)
-- =============================================================================

('google-analytics', 'Google Analytics', 'analytics',
 'Web analytics',
 'Track bot performance and user behavior with Google Analytics.',
 'https://www.gstatic.com/analytics-suite/header/suite/v2/ic_analytics.svg',
 true, 'oauth2', 'free', true, true,
 ARRAY['all'],
 ARRAY['track_event', 'pageviews', 'conversions', 'custom_dimensions'],
 'n8n-nodes-base.googleAnalytics', 88,
 '{"steps": ["Go to Google Analytics", "Admin > Property > Measurement Protocol API"]}'::jsonb,
 'https://developers.google.com/analytics/'),

('mixpanel', 'Mixpanel', 'analytics',
 'Product analytics',
 'Track user events and build funnels with Mixpanel.',
 'https://mixpanel.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['track_event', 'user_profiles', 'funnels'],
 'n8n-nodes-base.mixpanel', 80,
 '{"steps": ["Go to Settings > Project Settings", "Copy Project Token"]}'::jsonb,
 'https://developer.mixpanel.com/'),

('segment', 'Segment', 'analytics',
 'Customer data platform',
 'Collect, clean, and route your customer data with Segment.',
 'https://segment.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['track', 'identify', 'page', 'group'],
 'n8n-nodes-base.segment', 78,
 '{"steps": ["Go to Segment Workspace", "Sources > Add Source > HTTP API", "Copy Write Key"]}'::jsonb,
 'https://segment.com/docs/'),

('amplitude', 'Amplitude', 'analytics',
 'Product analytics',
 'Understand user behavior with Amplitude product analytics.',
 'https://amplitude.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['track_event', 'user_properties', 'revenue'],
 'n8n-nodes-base.amplitude', 75,
 '{"steps": ["Go to Settings > Projects", "Copy API Key"]}'::jsonb,
 'https://www.docs.developers.amplitude.com/'),

('hotjar', 'Hotjar', 'analytics',
 'Behavior analytics',
 'Track user behavior with heatmaps and recordings.',
 'https://www.hotjar.com/favicon.ico',
 true, 'api_key', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['events', 'identify', 'attributes'],
 'custom', 72,
 '{"steps": ["Go to Settings > Sites & Organizations", "Get Site ID"]}'::jsonb,
 'https://help.hotjar.com/hc/en-us/articles/115009336727'),

-- =============================================================================
-- SPECIALIZED / SOUTH AFRICAN (15 integrations)
-- =============================================================================

('shiplogic', 'ShipLogic', 'specialized',
 'SA shipping integration',
 'Track shipments and manage deliveries for South African e-commerce. Supports major SA couriers.',
 '/integrations/shiplogic.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['track_shipment', 'create_shipment', 'quotes', 'couriers'],
 'custom', 75,
 '{"steps": ["Contact ShipLogic for API access", "Complete merchant verification"]}'::jsonb,
 'https://www.shiplogic.com/'),

('pargo', 'Pargo', 'specialized',
 'SA pickup points',
 'Enable click-and-collect with Pargo pickup points across South Africa.',
 '/integrations/pargo.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['pickup_points', 'shipments', 'tracking'],
 'custom', 68,
 '{"steps": ["Contact Pargo for API access", "Get API credentials"]}'::jsonb,
 'https://www.pargo.co.za/'),

('uafrica', 'uAfrica', 'specialized',
 'SA courier aggregator',
 'Compare and book couriers from multiple South African shipping providers.',
 '/integrations/uafrica.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['quotes', 'shipments', 'tracking', 'couriers'],
 'custom', 65,
 '{"steps": ["Sign up at uafrica.com", "Get API credentials from dashboard"]}'::jsonb,
 'https://www.uafrica.com/'),

('whatsapp-cloud', 'WhatsApp Cloud API', 'specialized',
 'Official WhatsApp API',
 'Direct integration with WhatsApp Cloud API for business messaging.',
 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
 true, 'api_key', 'free', true, true,
 ARRAY['all'],
 ARRAY['send_message', 'templates', 'media', 'webhooks'],
 'custom', 95,
 '{"steps": ["Create Meta Business account", "Set up WhatsApp Business", "Get API credentials"]}'::jsonb,
 'https://developers.facebook.com/docs/whatsapp/cloud-api/'),

('bird-api', 'Bird (MessageBird)', 'specialized',
 'Omnichannel messaging',
 'Send messages across multiple channels with Bird (formerly MessageBird).',
 'https://bird.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['whatsapp', 'sms', 'voice', 'email'],
 'custom', 82,
 '{"steps": ["Log in to Bird Dashboard", "Go to Developers > API access", "Create API key"]}'::jsonb,
 'https://docs.bird.com/'),

('maps-google', 'Google Maps', 'specialized',
 'Location services',
 'Geocoding, directions, and place search with Google Maps.',
 'https://www.google.com/images/branding/product/2x/maps_96dp.png',
 true, 'api_key', 'freemium', false, true,
 ARRAY['taxi', 'restaurant', 'hotel', 'real_estate'],
 ARRAY['geocoding', 'directions', 'places', 'distance_matrix'],
 'n8n-nodes-base.googleMaps', 88,
 '{"steps": ["Go to Google Cloud Console", "Enable Maps APIs", "Create API key"]}'::jsonb,
 'https://developers.google.com/maps/'),

('openai', 'OpenAI', 'specialized',
 'AI & language models',
 'Enhance your bot with GPT-4 for intelligent conversations.',
 'https://openai.com/favicon.ico',
 true, 'api_key', 'paid', true, true,
 ARRAY['all'],
 ARRAY['chat', 'completions', 'embeddings', 'vision'],
 'n8n-nodes-base.openAi', 95,
 '{"steps": ["Go to platform.openai.com", "API Keys > Create new key"]}'::jsonb,
 'https://platform.openai.com/docs/'),

('anthropic', 'Claude (Anthropic)', 'specialized',
 'AI assistant',
 'Power your bot with Claude for safe and helpful AI responses.',
 'https://www.anthropic.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['all'],
 ARRAY['messages', 'completions'],
 'n8n-nodes-base.anthropic', 88,
 '{"steps": ["Go to console.anthropic.com", "Settings > API Keys > Create Key"]}'::jsonb,
 'https://docs.anthropic.com/'),

('quickbooks-sa', 'QuickBooks South Africa', 'specialized',
 'SA accounting software',
 'Manage invoices and accounting with QuickBooks for South African businesses.',
 'https://quickbooks.intuit.com/favicon.ico',
 true, 'oauth2', 'paid', false, true,
 ARRAY['all'],
 ARRAY['invoices', 'customers', 'payments', 'reports'],
 'n8n-nodes-base.quickBooks', 75,
 '{"steps": ["Create Intuit Developer account", "Create app", "Get OAuth credentials"]}'::jsonb,
 'https://developer.intuit.com/'),

('xero-sa', 'Xero', 'specialized',
 'Cloud accounting',
 'Connect Xero for invoicing, expenses, and financial reporting.',
 'https://www.xero.com/etc.clientlibs/xero/clientlibs/clientlib-site/resources/favicon.ico',
 true, 'oauth2', 'paid', false, true,
 ARRAY['all'],
 ARRAY['invoices', 'contacts', 'payments', 'reports'],
 'n8n-nodes-base.xero', 72,
 '{"steps": ["Go to Xero Developer Portal", "Create app", "Get OAuth credentials"]}'::jsonb,
 'https://developer.xero.com/'),

('sage-sa', 'Sage Business Cloud', 'specialized',
 'SA business software',
 'South African accounting and business management with Sage.',
 '/integrations/sage.png',
 true, 'oauth2', 'paid', false, false,
 ARRAY['all'],
 ARRAY['invoices', 'customers', 'products', 'payments'],
 'custom', 68,
 '{"steps": ["Contact Sage for API access", "Register as developer"]}'::jsonb,
 'https://developer.sage.com/'),

('zoom', 'Zoom', 'specialized',
 'Video conferencing',
 'Schedule and manage Zoom meetings from WhatsApp.',
 'https://zoom.us/favicon.ico',
 true, 'oauth2', 'freemium', false, true,
 ARRAY['all'],
 ARRAY['meetings', 'webinars', 'recordings'],
 'n8n-nodes-base.zoom', 80,
 '{"steps": ["Go to Zoom App Marketplace", "Build App", "Get credentials"]}'::jsonb,
 'https://marketplace.zoom.us/docs/api-reference/'),

('google-meet', 'Google Meet', 'specialized',
 'Video meetings',
 'Create and manage Google Meet video calls.',
 'https://www.gstatic.com/images/branding/product/2x/meet_48dp.png',
 true, 'oauth2', 'free', false, true,
 ARRAY['all'],
 ARRAY['create_meeting', 'calendar_event'],
 'custom', 78,
 '{"steps": ["Enable Google Calendar API", "Meetings are created via Calendar events"]}'::jsonb,
 'https://developers.google.com/calendar/api/guides/create-events#conferencing'),

('docusign', 'DocuSign', 'specialized',
 'Electronic signatures',
 'Send documents for signature via WhatsApp.',
 'https://www.docusign.com/favicon.ico',
 true, 'oauth2', 'paid', false, true,
 ARRAY['real_estate', 'all'],
 ARRAY['send_envelope', 'templates', 'status'],
 'n8n-nodes-base.docusign', 72,
 '{"steps": ["Create DocuSign Developer account", "Create integration key"]}'::jsonb,
 'https://developers.docusign.com/'),

('hellosign', 'Dropbox Sign (HelloSign)', 'specialized',
 'E-signatures',
 'Request signatures on documents through WhatsApp.',
 'https://www.hellosign.com/favicon.ico',
 true, 'api_key', 'paid', false, true,
 ARRAY['real_estate', 'all'],
 ARRAY['signature_requests', 'templates', 'status'],
 'custom', 68,
 '{"steps": ["Go to HelloSign Settings > API", "Get API key"]}'::jsonb,
 'https://developers.hellosign.com/');

-- =============================================================================
-- Create/Update Indexes for Performance
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_marketplace_category ON integration_marketplace(category);
CREATE INDEX IF NOT EXISTS idx_marketplace_featured ON integration_marketplace(is_featured);
CREATE INDEX IF NOT EXISTS idx_marketplace_popularity ON integration_marketplace(popularity_score DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_slug ON integration_marketplace(slug);
CREATE INDEX IF NOT EXISTS idx_marketplace_search ON integration_marketplace USING gin(to_tsvector('english', name || ' ' || description));

-- Reindex existing indexes
REINDEX INDEX idx_marketplace_category;
REINDEX INDEX idx_marketplace_featured;
REINDEX INDEX idx_marketplace_popularity;
REINDEX INDEX idx_marketplace_slug;
REINDEX INDEX idx_marketplace_search;

-- Show results
SELECT 'Comprehensive marketplace seeded with ' || COUNT(*)::text || ' integrations!' as result
FROM integration_marketplace;

-- Show category breakdown
SELECT category, COUNT(*) as count
FROM integration_marketplace
GROUP BY category
ORDER BY count DESC;
