-- Migration 008: Additional South African Integrations
-- Phase 2: Expand marketplace with SA-specific integrations
-- Created: 2026-01-18
-- Purpose: Add more South African business integrations

INSERT INTO integration_marketplace (
  slug, name, category, description, long_description, icon_url,
  requires_auth, auth_type, pricing_model, is_featured, is_direct_integration,
  recommended_for_verticals, supported_features, n8n_node_name, popularity_score,
  setup_instructions, documentation_url
) VALUES

-- =============================================================================
-- SOUTH AFRICAN PAYMENT GATEWAYS
-- =============================================================================

('iveri', 'iVeri', 'payment',
 'SA bank payment gateway',
 'Nedbank''s secure payment gateway for South African merchants. Supports 3D Secure and multiple card types.',
 '/integrations/iveri.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['card_payments', '3d_secure', 'refunds', 'recurring'],
 'custom', 72,
 '{"steps": ["Contact Nedbank for merchant account", "Apply for iVeri access", "Get API credentials"]}'::jsonb,
 'https://www.iveri.com/'),

('payu-sa', 'PayU South Africa', 'payment',
 'SA payment service provider',
 'PayU offers secure online payments for South African businesses with multiple payment methods.',
 '/integrations/payu.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['card_payments', 'eft', 'discovery_miles', 'mobicred', 'ebucks'],
 'custom', 75,
 '{"steps": ["Sign up at payu.co.za", "Complete verification", "Get Safe Key and API credentials"]}'::jsonb,
 'https://developers.payu.co.za/'),

('payfast', 'PayFast', 'payment',
 'SA online payment processor',
 'Popular South African payment gateway supporting cards, EFT, and Masterpass.',
 '/integrations/payfast.png',
 true, 'api_key', 'free', true, false,
 ARRAY['ecommerce', 'retail', 'gym', 'salon'],
 ARRAY['card_payments', 'instant_eft', 'masterpass', 'mobicred', 'subscriptions'],
 'custom', 85,
 '{"steps": ["Register at payfast.co.za", "Verify account", "Get Merchant ID and Passphrase"]}'::jsonb,
 'https://developers.payfast.co.za/'),

('zapper', 'Zapper', 'payment',
 'QR code & voucher payments',
 'South African QR code payments and voucher system for retail and restaurants.',
 '/integrations/zapper.png',
 true, 'api_key', 'free', false, false,
 ARRAY['retail', 'restaurant'],
 ARRAY['qr_payments', 'vouchers', 'loyalty', 'split_bills'],
 'custom', 68,
 '{"steps": ["Contact Zapper for merchant onboarding", "Get API credentials"]}'::jsonb,
 'https://www.zapper.com/'),

('masterpass-sa', 'Masterpass by Mastercard', 'payment',
 'Digital wallet payments',
 'Mastercard''s digital wallet for fast and secure online payments in South Africa.',
 '/integrations/masterpass.png',
 true, 'oauth2', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['wallet_payments', 'express_checkout', 'tokenization'],
 'custom', 65,
 '{"steps": ["Register as Masterpass merchant", "Complete integration", "Get API keys"]}'::jsonb,
 'https://masterpass.com/'),

('stitch', 'Stitch', 'payment',
 'Payment infrastructure API',
 'Modern payment infrastructure for South African businesses with instant EFT.',
 '/integrations/stitch.png',
 true, 'api_key', 'free', true, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['instant_pay', 'account_linking', 'balance_check', 'transactions'],
 'custom', 78,
 '{"steps": ["Sign up at stitch.money", "Complete KYC", "Get API credentials"]}'::jsonb,
 'https://stitch.money/docs/'),

-- =============================================================================
-- SOUTH AFRICAN E-COMMERCE & MARKETPLACES
-- =============================================================================

('makro', 'Makro Marketplace', 'ecommerce',
 'SA wholesale marketplace',
 'Connect to Makro''s marketplace for wholesale order management.',
 '/integrations/makro.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'inventory'],
 'custom', 62,
 '{"steps": ["Register as Makro seller", "Request API access", "Get credentials"]}'::jsonb,
 'https://www.makro.co.za/'),

('checkers-sixty60', 'Checkers Sixty60', 'ecommerce',
 'Grocery delivery integration',
 'Integration for Checkers Sixty60 grocery delivery service.',
 '/integrations/checkers.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['restaurant', 'retail'],
 ARRAY['orders', 'delivery_status', 'products'],
 'custom', 70,
 '{"steps": ["Partner with Shoprite Group", "Complete onboarding", "Get API access"]}'::jsonb,
 'https://www.sixty60.co.za/'),

('woolworths-dash', 'Woolworths Dash', 'ecommerce',
 'Premium grocery delivery',
 'Integration with Woolworths Dash for premium grocery delivery services.',
 '/integrations/woolworths.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['retail'],
 ARRAY['orders', 'delivery', 'products'],
 'custom', 68,
 '{"steps": ["Apply for Woolworths partnership", "Complete integration", "Get credentials"]}'::jsonb,
 'https://www.woolworths.co.za/'),

('superbalist', 'Superbalist', 'ecommerce',
 'SA fashion marketplace',
 'Connect to South Africa''s leading online fashion retailer.',
 '/integrations/superbalist.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['orders', 'products', 'inventory', 'returns'],
 'custom', 65,
 '{"steps": ["Apply as Superbalist seller", "Complete onboarding", "Get API access"]}'::jsonb,
 'https://superbalist.com/'),

('bidorbuy', 'bidorbuy', 'ecommerce',
 'SA auction & marketplace',
 'South Africa''s largest online auction and shopping site.',
 '/integrations/bidorbuy.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['listings', 'orders', 'bidding', 'messaging'],
 'custom', 60,
 '{"steps": ["Register as bidorbuy seller", "Apply for API access", "Get credentials"]}'::jsonb,
 'https://www.bidorbuy.co.za/'),

-- =============================================================================
-- SOUTH AFRICAN SHIPPING & LOGISTICS
-- =============================================================================

('courier-guy', 'The Courier Guy', 'specialized',
 'SA courier service',
 'Popular South African courier service for e-commerce deliveries.',
 '/integrations/courierguy.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['shipments', 'tracking', 'quotes', 'collections'],
 'custom', 80,
 '{"steps": ["Register at thecourierguy.co.za", "Apply for API access", "Get credentials"]}'::jsonb,
 'https://www.thecourierguy.co.za/'),

('fastway', 'Fastway Couriers SA', 'specialized',
 'Express courier service',
 'Fast and reliable courier services across South Africa.',
 '/integrations/fastway.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['shipments', 'tracking', 'quotes', 'pod'],
 'custom', 72,
 '{"steps": ["Contact Fastway for business account", "Get API credentials"]}'::jsonb,
 'https://www.fastway.co.za/'),

('dawn-wing', 'Dawn Wing', 'specialized',
 'National courier network',
 'One of South Africa''s largest courier networks.',
 '/integrations/dawnwing.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['shipments', 'tracking', 'quotes', 'returns'],
 'custom', 70,
 '{"steps": ["Register at dawnwing.co.za", "Complete business verification", "Get API access"]}'::jsonb,
 'https://www.dawnwing.co.za/'),

('aramex-sa', 'Aramex South Africa', 'specialized',
 'International logistics',
 'Global logistics and courier services with strong SA presence.',
 '/integrations/aramex.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['international_shipping', 'tracking', 'customs', 'returns'],
 'custom', 68,
 '{"steps": ["Register at aramex.co.za", "Get business account", "Request API access"]}'::jsonb,
 'https://www.aramex.co.za/'),

('postnet', 'PostNet', 'specialized',
 'Business services & shipping',
 'PostNet offers shipping, printing, and business services across SA.',
 '/integrations/postnet.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['domestic_shipping', 'international', 'tracking', 'pickup'],
 'custom', 65,
 '{"steps": ["Contact PostNet for business account", "Apply for API integration"]}'::jsonb,
 'https://www.postnet.co.za/'),

('paxi', 'PaXi', 'specialized',
 'Pep Stores parcel service',
 'Affordable parcel delivery through Pep and Ackermans stores.',
 '/integrations/paxi.png',
 true, 'api_key', 'free', false, false,
 ARRAY['ecommerce', 'retail'],
 ARRAY['send_parcel', 'track', 'store_locations'],
 'custom', 68,
 '{"steps": ["Register at paxi.co.za", "Get business account", "Access API"]}'::jsonb,
 'https://www.paxi.co.za/'),

-- =============================================================================
-- SOUTH AFRICAN ACCOUNTING & BUSINESS
-- =============================================================================

('pastel', 'Sage Pastel', 'specialized',
 'SA accounting software',
 'Popular South African accounting software for small businesses.',
 '/integrations/pastel.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['all'],
 ARRAY['invoices', 'quotes', 'customers', 'inventory', 'reports'],
 'custom', 78,
 '{"steps": ["Purchase Pastel subscription", "Enable API module", "Get API credentials"]}'::jsonb,
 'https://www.sage.com/en-za/'),

('sageone', 'Sage One (Sage Business Cloud)', 'specialized',
 'Cloud accounting SA',
 'Cloud-based accounting for South African small businesses and accountants.',
 '/integrations/sageone.png',
 true, 'oauth2', 'paid', false, false,
 ARRAY['all'],
 ARRAY['invoices', 'expenses', 'bank_feeds', 'vat_returns'],
 'custom', 75,
 '{"steps": ["Sign up for Sage One", "Go to Settings > API", "Generate credentials"]}'::jsonb,
 'https://accounting.sageone.co.za/'),

('draftworx', 'Draftworx', 'specialized',
 'SA compliance & reporting',
 'Statutory compliance and financial reporting for South African businesses.',
 '/integrations/draftworx.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['annual_returns', 'tax_compliance', 'cipc_submissions'],
 'custom', 60,
 '{"steps": ["Subscribe to Draftworx", "Request API access", "Configure integration"]}'::jsonb,
 'https://www.draftworx.com/'),

('simplypay', 'SimplePay', 'specialized',
 'SA payroll software',
 'Cloud payroll software designed for South African businesses.',
 '/integrations/simplypay.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['payroll', 'leave', 'payslips', 'tax_submissions'],
 'custom', 72,
 '{"steps": ["Sign up at simplepay.co.za", "Go to API Settings", "Generate API key"]}'::jsonb,
 'https://www.simplepay.co.za/'),

('payspace', 'PaySpace', 'specialized',
 'HR & payroll platform',
 'Enterprise HR and payroll solution for South African businesses.',
 '/integrations/payspace.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['payroll', 'hr_management', 'leave', 'time_attendance'],
 'custom', 68,
 '{"steps": ["Contact PaySpace for demo", "Subscribe to service", "Get API credentials"]}'::jsonb,
 'https://www.payspace.com/'),

-- =============================================================================
-- SOUTH AFRICAN FOOD & RESTAURANT
-- =============================================================================

('ubereats-sa', 'Uber Eats SA', 'specialized',
 'Food delivery platform',
 'Connect your restaurant to Uber Eats for delivery orders in South Africa.',
 '/integrations/ubereats.png',
 true, 'oauth2', 'paid', true, false,
 ARRAY['restaurant'],
 ARRAY['orders', 'menu_sync', 'delivery_status', 'analytics'],
 'custom', 88,
 '{"steps": ["Register as Uber Eats merchant", "Complete onboarding", "Access API via Uber Direct"]}'::jsonb,
 'https://www.ubereats.com/za'),

('mr-delivery', 'Mr D Food', 'specialized',
 'SA food delivery',
 'Takealot''s food delivery platform for South African restaurants.',
 '/integrations/mrd.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['restaurant'],
 ARRAY['orders', 'menu_management', 'delivery_tracking'],
 'custom', 85,
 '{"steps": ["Apply at mrd.food", "Complete restaurant verification", "Access merchant portal"]}'::jsonb,
 'https://www.mrd.food/'),

('bolt-food', 'Bolt Food SA', 'specialized',
 'Food delivery service',
 'Bolt''s food delivery service operating across South African cities.',
 '/integrations/boltfood.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['restaurant'],
 ARRAY['orders', 'menu_sync', 'delivery'],
 'custom', 75,
 '{"steps": ["Register as Bolt Food partner", "Complete onboarding", "Access API"]}'::jsonb,
 'https://food.bolt.eu/'),

('yumbi', 'YUMBI', 'specialized',
 'Restaurant ordering system',
 'South African restaurant ordering and delivery management platform.',
 '/integrations/yumbi.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['restaurant'],
 ARRAY['online_ordering', 'delivery', 'loyalty', 'pos_integration'],
 'custom', 70,
 '{"steps": ["Contact YUMBI sales", "Complete setup", "Get API credentials"]}'::jsonb,
 'https://www.yumbi.com/'),

('pilot', 'Pilot', 'specialized',
 'Restaurant POS system',
 'South African restaurant point-of-sale and management system.',
 '/integrations/pilot.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['restaurant'],
 ARRAY['pos', 'orders', 'inventory', 'reporting'],
 'custom', 68,
 '{"steps": ["Contact Pilot for demo", "Install POS system", "Enable API integration"]}'::jsonb,
 'https://www.pilot.co.za/'),

-- =============================================================================
-- SOUTH AFRICAN BOOKING & TRAVEL
-- =============================================================================

('travelstart', 'Travelstart', 'specialized',
 'SA travel booking',
 'South Africa''s leading online travel agency for flights and hotels.',
 '/integrations/travelstart.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['hotel', 'travel'],
 ARRAY['flights', 'hotels', 'car_rental', 'packages'],
 'custom', 72,
 '{"steps": ["Apply for affiliate/API access", "Complete agreement", "Get credentials"]}'::jsonb,
 'https://www.travelstart.co.za/'),

('lekkeslaap', 'LekkeSlaap', 'specialized',
 'SA accommodation booking',
 'Popular South African accommodation booking platform.',
 '/integrations/lekkeslaap.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['hotel', 'airbnb'],
 ARRAY['listings', 'bookings', 'availability', 'reviews'],
 'custom', 70,
 '{"steps": ["Register as property owner", "Apply for API access", "Get credentials"]}'::jsonb,
 'https://www.lekkeslaap.co.za/'),

('safarinow', 'SafariNow', 'specialized',
 'SA tourism platform',
 'South African tourism and accommodation booking platform.',
 '/integrations/safarinow.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['hotel', 'travel'],
 ARRAY['accommodations', 'activities', 'bookings'],
 'custom', 65,
 '{"steps": ["List on SafariNow", "Request API access", "Get integration credentials"]}'::jsonb,
 'https://www.safarinow.com/'),

('nightsbridge', 'NightsBridge', 'specialized',
 'SA channel manager',
 'South African booking and channel management for accommodations.',
 '/integrations/nightsbridge.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['hotel', 'airbnb'],
 ARRAY['channel_management', 'bookings', 'availability', 'rates'],
 'custom', 78,
 '{"steps": ["Sign up at nightsbridge.co.za", "Connect channels", "Enable API"]}'::jsonb,
 'https://www.nightsbridge.co.za/'),

-- =============================================================================
-- SOUTH AFRICAN COMMUNICATIONS & MARKETING
-- =============================================================================

('clickatell', 'Clickatell', 'communication',
 'SA messaging platform',
 'South African global messaging platform for SMS and chat commerce.',
 '/integrations/clickatell.png',
 true, 'api_key', 'paid', true, false,
 ARRAY['all'],
 ARRAY['sms', 'whatsapp', 'ussd', 'chat_commerce'],
 'custom', 82,
 '{"steps": ["Sign up at clickatell.com", "Get API key from dashboard"]}'::jsonb,
 'https://www.clickatell.com/'),

('bulksms', 'BulkSMS', 'communication',
 'Bulk SMS service',
 'South African bulk SMS service for marketing and notifications.',
 '/integrations/bulksms.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['bulk_sms', 'sms_api', 'delivery_reports', 'scheduling'],
 'custom', 70,
 '{"steps": ["Register at bulksms.co.za", "Add credits", "Get API credentials"]}'::jsonb,
 'https://www.bulksms.co.za/'),

('everlytic', 'Everlytic', 'communication',
 'SA marketing automation',
 'South African email and SMS marketing automation platform.',
 '/integrations/everlytic.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['email_marketing', 'sms_marketing', 'automation', 'analytics'],
 'custom', 75,
 '{"steps": ["Sign up at everlytic.com", "Go to Settings > API Keys", "Generate key"]}'::jsonb,
 'https://www.everlytic.com/'),

('grapevine', 'Grapevine', 'communication',
 'SA survey & feedback',
 'South African survey and customer feedback platform.',
 '/integrations/grapevine.png',
 true, 'api_key', 'paid', false, false,
 ARRAY['all'],
 ARRAY['surveys', 'feedback', 'nps', 'analytics'],
 'custom', 62,
 '{"steps": ["Sign up at grapevine.co.za", "Create survey", "Get API access"]}'::jsonb,
 'https://www.grapevine.co.za/'),

-- =============================================================================
-- SOUTH AFRICAN RIDE-HAILING & TRANSPORT
-- =============================================================================

('uber-sa', 'Uber SA', 'specialized',
 'Ride-hailing integration',
 'Integrate Uber for ride bookings and business travel in South Africa.',
 '/integrations/uber.png',
 true, 'oauth2', 'free', false, true,
 ARRAY['taxi', 'travel'],
 ARRAY['ride_requests', 'estimates', 'receipts', 'business_profiles'],
 'custom', 85,
 '{"steps": ["Register at developer.uber.com", "Create app", "Get OAuth credentials"]}'::jsonb,
 'https://developer.uber.com/'),

('bolt-rides', 'Bolt SA', 'specialized',
 'SA ride-hailing',
 'Bolt ride-hailing service integration for South African businesses.',
 '/integrations/bolt.png',
 true, 'api_key', 'free', false, false,
 ARRAY['taxi', 'travel'],
 ARRAY['ride_requests', 'estimates', 'driver_tracking'],
 'custom', 80,
 '{"steps": ["Apply for Bolt Business", "Complete verification", "Access API"]}'::jsonb,
 'https://bolt.eu/'),

('indriver-sa', 'inDrive SA', 'specialized',
 'Negotiable ride-hailing',
 'Ride-hailing app where passengers set their own prices.',
 '/integrations/indriver.png',
 true, 'api_key', 'free', false, false,
 ARRAY['taxi'],
 ARRAY['ride_requests', 'price_negotiation'],
 'custom', 65,
 '{"steps": ["Contact inDriver for business integration", "Complete setup"]}'::jsonb,
 'https://indrive.com/'),

-- =============================================================================
-- SOUTH AFRICAN BANKING & FINTECH
-- =============================================================================

('fnb-api', 'FNB Open Banking', 'specialized',
 'FNB banking integration',
 'First National Bank''s open banking APIs for South African businesses.',
 '/integrations/fnb.png',
 true, 'oauth2', 'free', false, false,
 ARRAY['all'],
 ARRAY['account_info', 'payments', 'statements', 'notifications'],
 'custom', 75,
 '{"steps": ["Apply at fnb.co.za developer portal", "Complete verification", "Get API access"]}'::jsonb,
 'https://www.fnb.co.za/'),

('nedbank-api', 'Nedbank API', 'specialized',
 'Nedbank open banking',
 'Nedbank''s open banking APIs for payments and account services.',
 '/integrations/nedbank.png',
 true, 'oauth2', 'free', false, false,
 ARRAY['all'],
 ARRAY['payments', 'account_info', 'statements'],
 'custom', 72,
 '{"steps": ["Register at developer.nedbank.co.za", "Create app", "Get credentials"]}'::jsonb,
 'https://developer.nedbank.co.za/'),

('investec-api', 'Investec Programmable Banking', 'specialized',
 'Programmable banking',
 'Investec''s programmable banking platform for developers.',
 '/integrations/investec.png',
 true, 'oauth2', 'free', true, false,
 ARRAY['all'],
 ARRAY['accounts', 'transfers', 'card_controls', 'webhooks'],
 'custom', 80,
 '{"steps": ["Open Investec account", "Enable programmable banking", "Get API keys"]}'::jsonb,
 'https://developer.investec.com/'),

('tymebank', 'TymeBank', 'specialized',
 'Digital bank integration',
 'South Africa''s digital bank with API access for businesses.',
 '/integrations/tymebank.png',
 true, 'api_key', 'free', false, false,
 ARRAY['all'],
 ARRAY['accounts', 'payments', 'notifications'],
 'custom', 68,
 '{"steps": ["Open TymeBank business account", "Apply for API access"]}'::jsonb,
 'https://www.tymebank.co.za/'),

('discovery-vitality', 'Discovery Vitality', 'specialized',
 'Rewards & wellness',
 'Discovery''s Vitality wellness and rewards program integration.',
 '/integrations/discovery.png',
 true, 'oauth2', 'paid', false, false,
 ARRAY['gym', 'medical'],
 ARRAY['rewards', 'fitness_tracking', 'health_assessments'],
 'custom', 70,
 '{"steps": ["Contact Discovery for partnership", "Complete integration agreement", "Get API access"]}'::jsonb,
 'https://www.discovery.co.za/');

-- Show results
SELECT 'Added ' || COUNT(*)::text || ' South African integrations!' as result
FROM integration_marketplace
WHERE slug IN (
  'iveri', 'payu-sa', 'payfast', 'zapper', 'masterpass-sa', 'stitch',
  'makro', 'checkers-sixty60', 'woolworths-dash', 'superbalist', 'bidorbuy',
  'courier-guy', 'fastway', 'dawn-wing', 'aramex-sa', 'postnet', 'paxi',
  'pastel', 'sageone', 'draftworx', 'simplypay', 'payspace',
  'ubereats-sa', 'mr-delivery', 'bolt-food', 'yumbi', 'pilot',
  'travelstart', 'lekkeslaap', 'safarinow', 'nightsbridge',
  'clickatell', 'bulksms', 'everlytic', 'grapevine',
  'uber-sa', 'bolt-rides', 'indriver-sa',
  'fnb-api', 'nedbank-api', 'investec-api', 'tymebank', 'discovery-vitality'
);

-- Show total count
SELECT 'Total marketplace integrations: ' || COUNT(*)::text as total
FROM integration_marketplace;

-- Show SA-specific integrations
SELECT 'South African integrations: ' || COUNT(*)::text as sa_count
FROM integration_marketplace
WHERE is_direct_integration = false OR slug LIKE '%sa%' OR slug LIKE 'paystack%' OR slug LIKE 'yoco%';
